image: python:3.11

stages:
  - test

full_test:
  stage: test
  before_script:
    - apt-get update && apt-get install -y libgl1
    - pip3 install --upgrade pip
    - pip3 install pytest
    - pip3 install .
  script:
    - pytest -vv tests